### ISSUE TITLE
Can't resolve the module

### ISSUE THREAD

**Issue by jasuno** [bennymeg/AcademicEmailVerifier#1]
<img width="1280" alt="screen shot 2019-01-14 at 11 13 24 pm" src="https://user-images.githubusercontent.com/29812661/51158334-0c0bde00-1852-11e9-9272-105daa9ff1a5.png">

i installed it like 3 times, but i still get this error. I know the module is there, because i can see it. Anyone have a solution?

**Comment by bennymeg** [comment]
This module is designed to work on Node.js environments (it dependent on fs library). React Native applications do not run in the Node.js environment (it is only used by the packager to actually serve and compile your application bundle). 

Please explore how to use fs inside React Native applications. ([https://www.npmjs.com/package/react-native-fs](this) might work).

Since it is not a problem with the module, I'll close that issue.
